version: '3.2'
services:
  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_TAG}
    ports:
    - 9093:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager   
    volumes:
    # - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    - ./alertmanager:/etc/alertmanager
    deploy: 
      mode: global
    restart: always
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    # - ./prometheus:/etc/prometheus:ro
    - ./prometheus:/etc/prometheus
  # amtool:
  #   build:
  #     context: amtool
  #   volumes:
  #   - ./amtool/config.yml:/etc/amtool/config.yml:ro
  hello:
    build:
      context: hello
      args:
        goPackage: github.com/prometheus-community/prometheus-playground/alertmanager/hello
        goVersion: 1.11
      cache_from:
      - golang:1.11
      - scratch
    ports:
    - 2112:2112
  webhook:
    build:
      context: webhook
      args:
        goPackage: github.com/prometheus-community/prometheus-playground/alertmanager/webhook
        goVersion: 1.11
      cache_from:
      - golang:1.11
      - scratch
    ports:
    - 5001:5001
  grafana:
    depends_on: [prometheus]
    ports:
      - "3000:3000"
    image: grafana/grafana:8.1.1
    volumes:
      - ./grafana:/etc/grafana:rw
    networks:
      - default
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel